@startuml maquinaEstadoEventoSismico
hide empty description
'Casos de uso:
'23: Registrar resultado de revisión manual
'24: Registrar evento sísmico
'25: Modificar evento sísmico
'27: Anular evento sísmico
'38: Verificar eventos sísmicos auto detectados
'39: Cerrar evento sísmico
'67: Registrar resultado de revisión de un evento sismico derivado

[*]-->AutoDetectado : 24. \n new() [magnitudSismo < 4.0]
[*]-->AutoConfirmado : 24. \n new() [magnitudSismo >= 4.0]
AutoDetectado-->PendienteRevision :  25. \n revisar() \n [tiempoEspera=5min] 
PendienteRevision-->BloqueadoRevision: 25 \n bloquear() [revisionSi=Si \n & tiempoEspera<5min]
PendienteRevision-->EventoSinRevision: 27. bloquear() [revisionSi=No \n & tiempoEspera=5min]
AutoDetectado --> BloqueadoRevision: 25. \n revisar() \n [tiempoEspera<5min]
BloqueadoRevision-->Confirmado: 23.\n confirmarDirecto()
BloqueadoRevision-->Rechazado:  23.\n rechazar()
BloqueadoRevision-->DerivadoExperto:  23.\n derivar()
DerivadoExperto-->Confirmado: 67. \n confirmarDerivado()
DerivadoExperto-->Rechazado: 67. \n rechazar()
Confirmado-->PendienteCierre: 23. \n pendienteCerrar()
AutoConfirmado-->PendienteCierre: 24.\n pendienteCerrar()
PendienteCierre --> Cerrado: 39. \n cerrar()
Cerrado --> [*]
EventoSinRevision --> [*]
Confirmado --> [*]
Rechazado --> [*]
@enduml

@startuml Parte_Dinámica_CU_23
skinparam roundcorner 20
skinparam maxmessagesize 60
autonumber
actor "__:AnalistaEnSismos__" as AES
create boundary "__:PantallaRegistrarResultado__" as PRR
AES --> PRR : opcRegistrarResultadoManual()
PRR -> PRR : abrirVentana()
create control "__:GestorRegistrarResultado__" as GRR
PRR --> GRR : newRevisiónManual()
GRR -> GRR : buscarEventosSísmicosSinRevision()
loop Eventos Sísmicos Auto Detectados
else Mientras existan eventos sísmicos
    entity "__:EventoSísmico__" as ES #LightCoral
    GRR --> ES : esPendienteRevisión()
    entity "__Evento:Estado__" as E
    ES --> E : sosPendienteRevisión()
    GRR --> ES : esAutodetectado()
    ES --> E : sosAutodetectado()
    GRR -> ES : getDatos()
    ES -> ES : getFechaHoraOcurrenciaEvento()
    ES -> ES : getLatitudEpicentro()
    ES -> ES : getLongitudEpicentro()
    ES -> ES : getLatitudHipocentro()
    ES -> ES : getLongitudHipocentro()
    ES -> ES : getValorMagnitud()
end
GRR -> GRR : ordenarEventosSísmicos()
GRR -> PRR : solicitarSelecciónEventoSísmico()
AES -> PRR : tomarSelecciónEventoSísmico()
PRR -> GRR : tomarSelecciónEventoSísmico()
GRR -> GRR : buscarEstadoBloqueadoEnRevision()
entity "__:Estado__" as Es #LightCoral
loop Buscar estado bloqueado en revisión
else Mientras existan estados
    GRR -> Es : sosÁmbitoEventoSísmico()
    GRR -> Es : sosBloqueadoEnRevisión()
end
GRR -> GRR : getFechaHoraActual()
GRR -> GRR : buscarEmpleadoLogueado()
entity "__Actual:Sesión__" as ASS
GRR -> ASS : getUsuarioLogueado()
entity "__Logueado:Usuario__" as US
ASS -> US : getEmpleado()
GRR -> GRR : bloquearEventoSísmico()
entity "__Selecc:EventoSísmico__" as SES
GRR -> SES : bloquear() 
loop Buscar último cambio estado
else Mientras existan cambios de estado
    entity "__:CambioEstado__" as CE #LightCoral
    SES -> CE : esEstadoActual() 
end
entity "__Actual:CambioEstado__" as ACE
SES -> ACE : setFechaHoraFin()
SES -> SES : crearCambioEstado()
create entity "__Bloqueado:CambioEstado__" as NCE
SES --> NCE: new()
SES -> SES : setEstado()
GRR -> GRR : buscarDatosSísmicos()
GRR -> SES : getDatosSísmicos()
entity "__:AlcanceSismo__" as AS
SES -> AS : getNombre()
entity "__:ClasificaciónSismo__" as CS
SES -> CS : getNombre()
entity "__:OrigenDeGeneración__" as OG
SES -> OG : getNombre()
loop Valores alcanzados sísmo
else Mientras existan series temporales
    entity "__:SerieTemporal__" as ST #LightCoral
    SES --> ST : getDatos()
    loop Valores muestras sísmicas
    else Mientras existan muestras sísmicas
        entity "__:MuestraSísmica__" as MS
        ST --> MS : getDatos()
        loop Valores detalle muestras sísmicas
        else Mientras existan detalles muestras sísmicas
            entity "__:DetalleMuestraSísmica__" as DMS
            MS --> DMS :  getDatos()
            entity "__:TipoDeDato__" as TD
            DMS --> TD :  getDenominación()
            DMS -> TD :  getNombreUnidadMedida()
            DMS -> TD :  getValorUmbral()
        end
    end
end

GRR -> GRR: ordenarPorCodigo()
GRR -> GRR : buscarDatosEstacion()
GRR -> ST : *getEstacionSismografica()
loop Buscar Sismografo
else mientras haya sismografos
    entity "__:Sismografo__" as S #LightCoral
    ST -> S : sosMiSismografo()
    ST -> S : getDatosEstacion()
    entity "__Sismografo:Estacion Sismologica__" as SSE
    S -> SSE : getNombre()
    S -> SSE : getCodigo()
end

GRR -> GRR : llamarCUGenerarSismograma()
create participant "GenerarSismograma" as GS
GRR -> GS : generarSismograma()
GRR -> PRR : mostrarDatos()
GRR -> PRR : solicitarSelecciónMapa()
AES -> PRR : tomarSelecciónMapa()
PRR -> GRR : tomarSeleccionMapa()
GRR -> PRR : solicitarModificaciónDatosES()
AES -> PRR : tomarModificaciónDatosES()
PRR -> GRR : tomarModificaciónDatosES()
GRR -> PRR : solicitarAcciónSobreEvento()
AES -> PRR : tomarAcciónSobreEvento()
PRR -> GRR : tomarAcciónSobreEvento()
GRR -> GRR : validarDatos()
GRR -> GRR : buscarEstadoRechazado()
loop Buscar estado rechazado
else Mientras existan estados
    GRR -> Es : sosÁmbitoEventoSísmico()
    GRR -> Es : sosRechazado()
end
GRR -> GRR :getFechaHoraActual()
GRR -> GRR : rechazarEventoSísmico()
entity "__Selecc:EventoSísmico__" as SES
GRR -> SES : rechazar()
SES -> NCE : setFechaHoraFin()
SES -> SES : crearCambioEstado()
entity "__Rechazado:CambioEstado__" as RCE
SES --> RCE : new()
GRR -> GRR : finCU()
@enduml

@startuml Parte_Estática_CU_23
hide <<Entity>> circle
hide <<Boundary>> circle
hide <<Control>> circle
class PantallaRegistrarRevisión<<Boundary>>{
    - opcCancelar
    - lblFechaHoraOcurrencia
    - lblLatitudEpicentro
    - lblLongitudEpicentro
    - lblLatidudHipocentro
    - lblLongitudHipocentro
    - opcVisualizarMapa
    - inputMagnitud
    - inputAlcance
    - inputOrigenGeneración
    - opcNoModificarDatos
    - opcConfirmarEvento
    - opcRechazarEvento
    - opcSolicitarRevisiónAExperto
    + 1. opcRegistrarResultadoManual()
    + 2. abrirVentana()
    + 17. solicitarSelecciónEventoSísmico()
    + 18. tomarSeleccionEventoSismico()
    + 54. mostrarDatos()
    + 55. solicitarSelecciónMapa()
    + 56. tomarSeleccionMapa()
    + 58. solicitarModificacionDatosES()
    + 59. tomarModificaciónDatosES()
    + 61. solicitarAcciónSobreEvento()
    + 62. tomarAcciónSobreEvento()
}

class GestorRegistrarRevisión<<Control>>{
    - fechaHoraOcurrencia
    - latitudEpicentro
    - longitudEpicentro
    - latidudHipocentro
    - longitudHipocentro
    - listaEventoSísmicoSinRevisión
    - eventoSísmicoSeleccionado
    - fechaHoraActual
    - ASLogueado
    - estadoRechazado
    - estadoBloqueado
    - listaDatosSísmicos
    - listaSeriesTemporales
    - estaciónSismográfica
    - sismograma
    - mapaSeleccionado
    - acciónSobreEvento
    - estaciónSismográficaModificada
    + 3. newRevisiónManual()
    + 4. buscarEventosSísmicosSinRevision()
    + 16. ordenarEventosSísmicos()
    + 19. tomarSelecciónEventoSísmico()
    + 20. buscarEstadoBloqueadoEnRevision()
    + 23. getFechaHoraActual()
    + 24. buscarEmpleadoLogueado()
    + 27. bloquearEventoSismico()
    + 34. buscarDatosSismicos()
    + 46. buscarDatosEstacion()
    + 45. ordenarPorCodigo() 
    + 52. llamarCUGenerarSismograma()
    + 57. tomarSelecciónMapa()
    + 60. tomarModificaciónDatosES()
    + 63. tomarAcciónSobreEvento()
    + 64. validarDatos()
    + 65. buscarEstadoRechazado()
    + 69. rechazarEventoSismico()
    + 74. finCU()
}

class EventoSísmico<<Entity>>{
    - fechaHoraOcurrencia
    - latitudEpicentro
    - longitudEpicentro
    - latidudHipocentro
    - longitudHipocentro
    - valorMagnitud
    + 5. esPendienteRevisión()
    + 7. esAutodetectado()
    + 9. getDatos()
    + 10. getFechaHoraOcurrenciaEvento()
    + 11. getLatitudLepicentro()
    + 12. getLongitudEpicentro()
    + 13. getLatitudHipocentro()
    + 14. getLongitudHipocentro()
    + 15. getValorMagnitud()
    + 28. bloquear()
    + 31. crearCambioEstado()
    + 32. new()
    + 33. setEstado()
    + 35. getDatosSísmicos()
    + 70. rechazar()
    + revisar()
    + derivar()
    + confirmarDerivado()
    + confirmarDirecto()
    + pendienteCerrar()
    + cerrar()
}

class Estado<<Entity>>{
    - ámbito
    - nombre
    + 6. sosPendienteRevisión()
    + 8. sosAutodetectado()
    + 21. sosÁmbitoEventoSísmico()
    + 22. sosBloqueadoEnRevisión()
    + 67. sosRechazado()
}

class CambioEstado<<Entity>>{
    - fechaHoraInicio
    - fechaHoraFin
    + 29. esEstadoActual()
    + 30. setFechaHoraFin()
    + 32. new()
}

class AlcanceSismo<<Entity>>{
    - nombre
    + 36. getNombre()
}

class ClasificaciónSismo<<Entity>>{
    - nombre
    + 37. getNombre()
}

class OrigenDeGeneración<<Entity>>{
    - nombre
    + 38. getNombre()
}

class SerieTemporal<<Entity>>{
    + 39. getDatos()
    + 47. getEstaciónSismográfica()
}

class MuestraSísmica<<Entity>>{
    + 40. getDatos()
}

class DetalleMuestraSísmica<<Entity>>{
    + 41. getDatos()
}

class TipoDeDato<<Entity>>{
    - denominación
    - nombreUnidadMedida
    - valorUmbral
    + 42. getDenominación()
    + 43. getNombreUnidadMedida()
    + 44. getValorUmbral()
}

class Sesion<<Entity>>{
    - fechaHoraInicio
    - fechaHoraFin
    + 25. getUsuarioLogueado()
}

class Usuario<<Entity>>{
    + 26. getEmpleado()
}

class Empleado<<Entity>>{
    - nombre
    - apellido
    - mail
    - telefono 
}

class Sismografo<<Entity>>{
    + 48. sosMiSismográfo()
    + 49. getDatosEstación()
}

class EstaciónSismológica<<Entity>>{
    - nombre
    - código
    + 50. getNombre()
    + 51. getCódigo()
}
Sesion "usuario" --> "1" Usuario
Usuario "empleado" --> "1" Empleado
PantallaRegistrarRevisión ..> GestorRegistrarRevisión
GestorRegistrarRevisión ..> Sesion
GestorRegistrarRevisión ..> PantallaRegistrarRevisión
GestorRegistrarRevisión ..> EventoSísmico
EventoSísmico "estado" --> "1" Estado
EventoSísmico "cambioEstado" --> "1..*" CambioEstado
EventoSísmico "alcanceSismo" --> "1" AlcanceSismo
EventoSísmico "clasificaciónSismo" --> "1" ClasificaciónSismo
EventoSísmico "origenDeGeneración" --> "1" OrigenDeGeneración
EventoSísmico "serieTemporal" --> "1..*" SerieTemporal
CambioEstado "empleado" --> "1" Empleado
CambioEstado "estado" --> "1" Estado
SerieTemporal "muestraSísmica" o-- "1..*" MuestraSísmica
SerieTemporal ..> Sismografo
Sismografo "serieTemporal" --> "1..*" SerieTemporal 
Sismografo "estaciónSismológica" --> "1" EstaciónSismológica
MuestraSísmica "detalleMuestraSísmica" o-- "1..*" DetalleMuestraSísmica
DetalleMuestraSísmica "tipoDeDato" --> "1" TipoDeDato
@enduml 